services:
  db:
    container_name: product
    image: postgres:16.0-alpine
    shm_size: 1gb
    env_file:
      ./env/db.env
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
      - ./volumes/dump/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "1432:5432"
  service:
    container_name: 3b_api_service
    restart: always
    build: ./app
    env_file:
      - ./env/service.env
    # command: ["sh","run.sh"]
    ports:
      - "8200:5000"
    depends_on:
      - db
